[package]
name = "microcosm-perf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_cpus = "1.13.1"
itertools = "0.10.3"
colour = "0.6.0"
rustc-hash = "1.1.0"
chrono = "0.4.19"